name: rest_verision_3
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.5.3+2
  animated_bottom_navigation_bar: 1.1.0
  flutter_animated_dialog: 2.0.1
  getwidget: 3.0.1
  badges: 2.0.3
  font_awesome_flutter: 10.1.0
  google_fonts: 3.0.1
  dio: 4.0.6
  json_serializable: 6.3.1
  cached_network_image: 3.2.1
  lottie: 1.4.2
  flutter_switch: ^0.3.2
  image_picker: any
  image_cropper: ^3.0.0
  shimmer: ^2.0.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  awesome_dialog: 3.0.2
  rounded_loading_button: 2.1.0
  socket_io_client: 2.0.0
  ticket_widget: 0.0.1
  intl: 0.17.0
  audioplayers: 1.1.1
  flutter_picker: ^2.0.5
  dropdown_button2: ^1.8.9
  fluttertoast: ^8.1.1
  internet_connection_checker: ^1.0.0+1
  flutter_speed_dial: ^6.2.0
  flutter_native_splash: ^2.2.14
  blue_thermal_printer: ^1.2.3 #For Android
  screenshot: ^1.2.3 #for widget to image
  flutter_pos_printer_platform: ^1.0.11 #For IOS & Windows
  esc_pos_utils: ^1.1.0 #For IOS & Windows
  flutter: 
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/image/welcome_splash.png



dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
    - assets/image/food/
    - assets/lottie/
    - assets/sounds/
  uses-material-design: true

